Script started on 2023-01-20 13:00:40-06:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="80" LINES="24"]
]777;notify;Command completed;exit\]777;precmd\]0;centos@localhost:/home/centos\]7;file://localhost/home/centos\[?2004h[root@localhost centos]# ldd project1
[?2004l]777;preexec\	linux-vdso.so.1 (0x00007ffdb65fe000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f4f27680000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f4f27400000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4f27767000)
]777;notify;Command completed;ldd project1\]777;precmd\]0;centos@localhost:/home/centos\]7;file://localhost/home/centos\[?2004h[root@localhost centos]# exit
[?2004l]777;preexec\exit

Script done on 2023-01-20 13:00:55-06:00 [COMMAND_EXIT_CODE="0"]
